import { Router } from 'express';
import { ContentController } from '../controllers/contentController.js';
import { authenticateToken, requireAdmin } from '../middleware/auth.js';
import { paginationValidation, handleValidationErrors } from '../middleware/validation.js';
import { adminLimiter } from '../middleware/rateLimit.js';
const router = Router();
router.use(authenticateToken);
router.use(requireAdmin);
router.get('/funding-opportunities', adminLimiter, paginationValidation, handleValidationErrors, ContentController.getFundingOpportunities);
router.post('/funding-opportunities', adminLimiter, ContentController.createFundingOpportunity);
router.put('/funding-opportunities/:id', adminLimiter, ContentController.updateFundingOpportunity);
router.delete('/funding-opportunities/:id', adminLimiter, ContentController.deleteFundingOpportunity);
router.get('/news-articles', adminLimiter, paginationValidation, handleValidationErrors, ContentController.getNewsArticles);
router.post('/news-articles', adminLimiter, ContentController.createNewsArticle);
router.put('/news-articles/:id', adminLimiter, ContentController.updateNewsArticle);
router.delete('/news-articles/:id', adminLimiter, ContentController.deleteNewsArticle);
router.get('/events', adminLimiter, paginationValidation, handleValidationErrors, ContentController.getEvents);
router.post('/events', adminLimiter, ContentController.createEvent);
router.put('/events/:id', adminLimiter, ContentController.updateEvent);
router.delete('/events/:id', adminLimiter, ContentController.deleteEvent);
export default router;
//# sourceMappingURL=content.js.map