-- Populate Network Companies with existing Shared Wealth Network data

INSERT INTO public.network_companies (
  name, sector, country, description, employees, shared_value, impact_score, 
  joined_date, website, logo, highlights, location, status, is_shared_wealth_licensed
) VALUES 
  (
    'Shared Wealth International Ltd',
    'Social Enterprise, Equitable Finance',
    'United Kingdom',
    'The overarching entity driving the Shared Wealth model globally. Core Shared Wealth Model implementation with global partnerships and strategic development.',
    50,
    '€5M',
    9.2,
    '2018',
    'https://sharedwealth.net',
    '/lovable-uploads/shared-wealth-logo.png',
    ARRAY['Core Shared Wealth Model', 'Global Partnerships', 'Strategic Development'],
    'Global (UK registered)',
    'active',
    true
  ),
  (
    'SEi Caledonia Ltd',
    'Social Enterprise, Regional Development',
    'United Kingdom',
    'Supports political engagement and JV exploration for Pathway in Scotland. Regional development focused on Scottish market.',
    15,
    '€750K',
    8.5,
    '2019',
    'https://seicaledonia.com',
    '/lovable-uploads/sei-caledonia-logo.png',
    ARRAY['Scottish Pathway Support', 'Political Engagement', 'JV Exploration'],
    'Scotland, UK',
    'active',
    true
  ),
  (
    'Spark CIC',
    'Charity, Social Enterprise',
    'United Kingdom',
    'Part of the Shared Wealth Group, focusing on charitable initiatives and social enterprise development.',
    10,
    '€300K',
    8.0,
    '2017',
    'https://sparkcic.org',
    '/lovable-uploads/spark-cic-logo.png',
    ARRAY['Shared Wealth Group', 'Charitable Initiatives', 'Social Enterprise'],
    'UK',
    'active',
    true
  ),
  (
    'LocoSoco PLC',
    'UK Public Limited Company',
    'United Kingdom',
    'Public limited company within the Shared Wealth Group, operating with shared wealth principles.',
    120,
    '€2.5M',
    7.8,
    '2016',
    'https://locosoco.com',
    '/lovable-uploads/locosoco-logo.png',
    ARRAY['Shared Wealth Group', 'Public Company', 'Shared Principles'],
    'UK',
    'active',
    true
  ),
  (
    'World Health Innovation Summit (WHIS)',
    'Community Interest Company, Health',
    'United Kingdom',
    'Community Interest Company focused on health innovation and affordable housing for key workers. Currently in discussions with Irish Government.',
    30,
    '€1.2M',
    8.9,
    '2017',
    'https://whis.org',
    '/lovable-uploads/whis-logo.png',
    ARRAY['Health Innovation', 'Affordable Housing', 'Irish Government Talks'],
    'UK/International',
    'active',
    true
  ),
  (
    'Nigerian Capital Development Fund (NCDF)',
    'Nigerian Company, Capital Development',
    'Nigeria',
    'Part of Shared Wealth Group, supporting seed investment mobilization and capital development in Nigeria.',
    40,
    '€1.8M',
    8.7,
    '2018',
    'https://ncdf.ng',
    '/lovable-uploads/ncdf-logo.png',
    ARRAY['Shared Wealth Group', 'Seed Investment', 'Capital Development'],
    'Nigeria',
    'active',
    true
  ),
  (
    'Media Cultured Ltd',
    'Community Interest Company, Media',
    'United Kingdom',
    'Community Interest Company arranging meetings with leaders and public engagement for Islamic community.',
    20,
    '€600K',
    7.5,
    '2017',
    'https://mediacultured.org',
    '/lovable-uploads/media-cultured-logo.png',
    ARRAY['Leader Engagement', 'Public Engagement', 'Islamic Community'],
    'UK',
    'active',
    true
  ),
  (
    'Pathway Points Ltd (Pathway)',
    'Housing & Finance Model',
    'United Kingdom',
    'Innovative housing approach that turns renters into owners. Community wealth building through innovative housing and finance model.',
    70,
    '€3.5M',
    9.5,
    '2025',
    'https://pathwaypoints.org',
    '/lovable-uploads/pathway-logo.png',
    ARRAY['Renters to Owners', 'Innovative Housing', 'Community Wealth Building'],
    'UK & International',
    'active',
    true
  ),
  (
    'Sustainable-Roots Limited (SRL)',
    'Company Limited by Shares',
    'United Kingdom',
    'Company Limited by Shares supporting Pathway Points initiatives and sustainable development.',
    5,
    '€150K',
    7.0,
    '2024',
    'https://sustainable-roots.co.uk',
    '/lovable-uploads/srl-logo.png',
    ARRAY['Pathway Support', 'Sustainable Development', 'Limited Company'],
    'UK',
    'active',
    true
  ),
  (
    'Tallarna Limited',
    'Company Limited by Shares',
    'United Kingdom',
    'Supports Pathway Points and explores Pathway Club-owned enterprises for property refurbishment and eco-fit works.',
    25,
    '€800K',
    8.2,
    '2024',
    'https://tallarna.com',
    '/lovable-uploads/tallarna-logo.png',
    ARRAY['Pathway Support', 'Property Refurbishment', 'Eco-fit Works'],
    'UK',
    'active',
    true
  ),
  (
    'Life Sciences Healthcare (LSH)',
    'Company Limited by Shares',
    'United Kingdom',
    'Healthcare company supporting Pathway Points initiatives and life sciences development.',
    50,
    '€1.5M',
    8.0,
    '2023',
    'https://lifescienceshealthcare.co.uk',
    '/lovable-uploads/lsh-logo.png',
    ARRAY['Pathway Support', 'Healthcare', 'Life Sciences'],
    'UK',
    'active',
    true
  ),
  (
    'Two Hands Consultancy Limited (2HC)',
    'Company Limited by Shares, Consultancy',
    'United Kingdom',
    'Consultancy and training company supporting Pathway Points, delivering training through remote/AI tutors.',
    12,
    '€400K',
    7.9,
    '2024',
    'https://twohandsconsultancy.co.uk',
    '/lovable-uploads/2hc-logo.png',
    ARRAY['Pathway Support', 'Consultancy', 'AI Training'],
    'UK',
    'active',
    true
  ),
  (
    'Maven Housing Limited (MHL)',
    'Company Limited by Shares, Housing',
    'United Kingdom',
    'Housing company supporting Pathway Points initiatives and housing development.',
    8,
    '€250K',
    7.3,
    '2024',
    'https://mavenhousing.co.uk',
    '/lovable-uploads/mhl-logo.png',
    ARRAY['Pathway Support', 'Housing Development', 'Limited Company'],
    'UK',
    'active',
    true
  ),
  (
    'Terratai Ltd',
    'Flagship Shared Wealth Enterprise',
    'United Kingdom',
    'Flagship Shared Wealth Enterprise transitioning to Shared Wealth model, opening ownership/governance, considering phantom shares, actively participating in inclusive decision-making models.',
    35,
    '€1.0M',
    9.1,
    '2025',
    'https://terratai.com',
    '/lovable-uploads/terratai-logo.png',
    ARRAY['Shared Wealth Model', 'Phantom Shares', 'Inclusive Decision-Making'],
    'UK',
    'active',
    true
  ),
  (
    'York University',
    'Academia, Research',
    'United Kingdom',
    'Academic institution collaborating to establish Pathway Chapter, engaging students and stakeholders in housing issues.',
    0,
    '€0',
    8.5,
    '2023',
    'https://york.ac.uk',
    '/lovable-uploads/york-university-logo.png',
    ARRAY['Pathway Chapter', 'Student Engagement', 'Housing Research'],
    'York, UK',
    'active',
    true
  ),
  (
    'Community First Credit Union',
    'Financial Services, Credit Union',
    'United Kingdom',
    'Credit union collaborating to develop a credit union distribution partner for Pathway.',
    60,
    '€2.0M',
    8.8,
    '2024',
    'https://communityfirstcu.co.uk',
    '/lovable-uploads/community-first-logo.png',
    ARRAY['Pathway Distribution', 'Credit Union', 'Financial Services'],
    'UK',
    'active',
    true
  ),
  (
    'Solar Ear UK',
    'Health Tech',
    'United Kingdom',
    'Health technology company serving as a third-party partner in the Shared Wealth network.',
    18,
    '€500K',
    7.6,
    '2023',
    'https://solarearuk.com',
    '/lovable-uploads/solar-ear-logo.png',
    ARRAY['Health Tech', 'Third-party Partner', 'Innovation'],
    'UK',
    'active',
    true
  ),
  (
    'Whitby Shared Wealth Social Enterprise',
    'Social Enterprise',
    'United Kingdom',
    'Local social enterprise in Whitby serving as a third-party partner in the Shared Wealth network.',
    8,
    '€200K',
    7.2,
    '2023',
    'https://whitbysharedwealth.org',
    '/lovable-uploads/whitby-logo.png',
    ARRAY['Local Enterprise', 'Third-party Partner', 'Community Focus'],
    'Whitby, UK',
    'active',
    true
  ),
  (
    'SEi Middle East',
    'Social Enterprise, Regional Development',
    'Middle East',
    'Regional development partner for collaboration in the Partnership Agreement, focusing on Middle Eastern markets.',
    28,
    '€900K',
    8.4,
    '2024',
    'https://seimiddleeast.org',
    '/lovable-uploads/sei-middle-east-logo.png',
    ARRAY['Regional Development', 'Third-party Partner', 'Middle East Focus'],
    'Middle East',
    'active',
    true
  ); 