// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewqwjduvjkddknpqpmfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cXdqZHV2amtkZGtucHFwbWZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTczMTEsImV4cCI6MjA2NzkzMzMxMX0.v6MDuvJaCWbczDW8KWoUUSGKFeaF_pXXP2N5yHPxmtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});