// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ewqwjduvjkddknpqpmfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cXdqZHV2amtkZGtucHFwbWZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTczMTEsImV4cCI6MjA2NzkzMzMxMX0.v6MDuvJaCWbczDW8KWoUUSGKFeaF_pXXP2N5yHPxmtY";

console.log('Supabase URL:', SUPABASE_URL);
console.log('Supabase Key exists:', !!SUPABASE_PUBLISHABLE_KEY);

// Create a safe storage wrapper
const createSafeStorage = () => {
  if (typeof window !== 'undefined' && window.localStorage) {
    console.log('Using localStorage for session storage');
    return window.localStorage;
  }
  console.log('localStorage not available, using memory storage');
  return {
    getItem: (key: string) => null,
    setItem: (key: string, value: string) => {},
    removeItem: (key: string) => {},
    clear: () => {},
    key: (index: number) => null,
    length: 0
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

console.log('Supabase client created successfully');